clean:

depend:

all:

install:

install_tar:
	rm -f add-file-voice_echo_canceler_lib
	touch add-file-voice_echo_canceler_lib
	tar czf  add-file-voice_echo_canceler_lib

gpl_tar:
	rm -f no_gpl_components
	touch no_gpl_components
	tar czf  add-file-voice_echo_canceler_lib

