#! /bin/sh

KERNEL_CLASS=$1
DRIVER_NAME=$2

if [ -z "$KERNEL_CLASS" ] ; then
    KERNEL_CLASS=26
fi

for i in `find . -name Makefile.$KERNEL_CLASS` ; do
    dest=${i%.$KERNEL_CLASS}
    source="`pwd`/$i"
    rm -f $dest
    ln -fvs $source $dest
done

exit 0
