#
# Makefile for the ARC prom monitor library routines under Linux.
#

obj-y	+= prom.o setup.o irq.o int-handler.o plat_time.o platform.o fusiv_mtd.o ikan_gpio.o ikan_clk.o
# serial.o
#
# Makefile for the ARC prom monitor library routines under Linux.
#

obj-y	+= prom.o setup.o irq.o int-handler.o plat_time.o platform.o
# serial.o
