#! /bin/sh

KERNEL_CLASS=$1
DRIVER_NAME=$2

if [ -z "$KERNEL_CLASS" ] ; then
    KERNEL_CLASS=26
fi

for i in `find . -name Makefile.$KERNEL_CLASS` ; do
    dest=${i%.$KERNEL_CLASS}
    source="`pwd`/$i"
    rm -f $dest
    ln -fvs $source $dest
done

ln -fs `pwd`/linux_ubik2_debug.h ../../../include/linux/ubik2_debug.h 
ln -fs `pwd`/linux_ubik2_interface.h ../../../include/linux/ubik2_interface.h 
ln -fs `pwd`/linux_ubik2_ul.h ../../../include/linux/ubik2_ul.h 
ln -fs `pwd`/linux_pcmlink_ul.h ../../../include/linux/pcmlink_ul.h 

exit 0
