#
#/* Copyright (C) 2006 Ikanos Communications
# * See IKANOS_PROP_LICENSE.txt for license information. */
#

include .config

obj-$(CONFIG_FUSIV_LIBRARY) += kernel/drivers/opensrc/
obj-$(CONFIG_FUSIV_LIBRARY) += kernel/ap_code/lib/
obj-$(CONFIG_FUSIV_BMDRIVER) += kernel/drivers/bm/
obj-$(CONFIG_FUSIV_KERNEL_ETHERNET) += kernel/drivers/ethdriver/
obj-$(CONFIG_FUSIV_KERNEL_PERI_AP) += kernel/drivers/peri_ap/
obj-$(CONFIG_FUSIV_KERNEL_ATM) += kernel/drivers/atm/
obj-$(CONFIG_FUSIV_TIMERS) += kernel/drivers/timerlib/
obj-$(CONFIG_FUSIV_KERNEL_AP_2_AP) += kernel/drivers/ap2ap/
obj-$(CONFIG_FUSIV_KERNEL_DSP) += kernel/drivers/voice/ipvoice/
obj-$(CONFIG_FUSIV_KERNEL_UART2) += kernel/drivers/uart2/
obj-$(CONFIG_BT_HCI_FUSIV_UART2)    += kernel/drivers/btuart/
obj-$(CONFIG_FUSIV_KERNEL_PPPOE_RELAY) += kernel/drivers/pppoer/
obj-$(CONFIG_FUSIV_KERNEL_MONIF) += kernel/drivers/monif/
obj-$(CONFIG_FUSIV_KERNEL_BME) += kernel/drivers/bmedriver/
obj-$(CONFIG_FUSIV_KERNEL_BME_DRIVER_VX180) += kernel/drivers/bmedriver/
obj-$(CONFIG_FUSIV_KERNEL_BME_DRIVER_VX180) += kernel/drivers/vdsldriver/
obj-$(CONFIG_FUSIV_KERNEL_ACL) += kernel/drivers/acl_ap/
obj-$(CONFIG_FUSIV_KERNEL_POLICY_VLAN) += kernel/drivers/policyVlan/

